// Generated by CoffeeScript 1.6.1

/* 
# ------------------------------------------------------------
# downplayed - downplay parser 
# ------------------------------------------------------------
# inspired by marked
# written in coffeescript
# ------------------------------------------------------------
*/


(function() {

  (function() {
    var grammar, sample;
    grammar = {
      header: /h{1,4}|h[1-4]\s.+/,
      paragraph: /(p?|p\s?)/
    };
    return sample = "h header\n p test";
  });

}).call(this);
