// Generated by CoffeeScript 1.6.1

/* 
# ------------------------------------------------------------
# downplayed - downplay parser 
# ------------------------------------------------------------
# inspired by marked
# written in coffeescript
# ------------------------------------------------------------
*/


(function() {

  (function() {
    var grammar, output, sample;
    grammar = {
      header: /h{1,4}|h[1-4]\s.+/,
      paragraph: /(p?|p\s?)/
    };
    sample = "h header\n p test";
    output = sample.replace(header.grammer, "<h1>$1</h1>");
    return console.log(output);
  });

}).call(this);
